/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStrategyRouteImport } from './routes/app.strategy'
import { Route as AppRidersRouteImport } from './routes/app.riders'
import { Route as AppRegisteredRidersRouteImport } from './routes/app.registered-riders'
import { Route as AppProvidersRouteImport } from './routes/app.providers'
import { Route as AppIncidentsRouteImport } from './routes/app.incidents'
import { Route as AppFacilityRouteImport } from './routes/app.facility'
import { Route as AppDriverRouteImport } from './routes/app.driver'
import { Route as AppDispatchRouteImport } from './routes/app.dispatch'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCaregiverRouteImport } from './routes/app.caregiver'
import { Route as AppBrokerRouteImport } from './routes/app.broker'
import { Route as AppBookRouteImport } from './routes/app.book'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAccountabilityRouteImport } from './routes/app.accountability'
import { Route as AppRegisteredRidersIndexRouteImport } from './routes/app.registered-riders.index'
import { Route as AppRidersRiderIdRouteImport } from './routes/app.riders.$riderId'
import { Route as AppRegisteredRidersNewRouteImport } from './routes/app.registered-riders.new'
import { Route as AppRegisteredRidersRiderIdRouteImport } from './routes/app.registered-riders.$riderId'
import { Route as AppLiveGpsRideIdRouteImport } from './routes/app.live-gps.$rideId'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStrategyRoute = AppStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => AppRoute,
} as any)
const AppRidersRoute = AppRidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisteredRidersRoute = AppRegisteredRidersRouteImport.update({
  id: '/registered-riders',
  path: '/registered-riders',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersRoute = AppProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppFacilityRoute = AppFacilityRouteImport.update({
  id: '/facility',
  path: '/facility',
  getParentRoute: () => AppRoute,
} as any)
const AppDriverRoute = AppDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatchRoute = AppDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCaregiverRoute = AppCaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => AppRoute,
} as any)
const AppBrokerRoute = AppBrokerRouteImport.update({
  id: '/broker',
  path: '/broker',
  getParentRoute: () => AppRoute,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountabilityRoute = AppAccountabilityRouteImport.update({
  id: '/accountability',
  path: '/accountability',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisteredRidersIndexRoute =
  AppRegisteredRidersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppRegisteredRidersRoute,
  } as any)
const AppRidersRiderIdRoute = AppRidersRiderIdRouteImport.update({
  id: '/$riderId',
  path: '/$riderId',
  getParentRoute: () => AppRidersRoute,
} as any)
const AppRegisteredRidersNewRoute = AppRegisteredRidersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRegisteredRidersRoute,
} as any)
const AppRegisteredRidersRiderIdRoute =
  AppRegisteredRidersRiderIdRouteImport.update({
    id: '/$riderId',
    path: '/$riderId',
    getParentRoute: () => AppRegisteredRidersRoute,
  } as any)
const AppLiveGpsRideIdRoute = AppLiveGpsRideIdRouteImport.update({
  id: '/live-gps/$rideId',
  path: '/live-gps/$rideId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/accountability': typeof AppAccountabilityRoute
  '/app/audit': typeof AppAuditRoute
  '/app/book': typeof AppBookRoute
  '/app/broker': typeof AppBrokerRoute
  '/app/caregiver': typeof AppCaregiverRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/driver': typeof AppDriverRoute
  '/app/facility': typeof AppFacilityRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/registered-riders': typeof AppRegisteredRidersRouteWithChildren
  '/app/riders': typeof AppRidersRouteWithChildren
  '/app/strategy': typeof AppStrategyRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/live-gps/$rideId': typeof AppLiveGpsRideIdRoute
  '/app/registered-riders/$riderId': typeof AppRegisteredRidersRiderIdRoute
  '/app/registered-riders/new': typeof AppRegisteredRidersNewRoute
  '/app/riders/$riderId': typeof AppRidersRiderIdRoute
  '/app/registered-riders/': typeof AppRegisteredRidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/accountability': typeof AppAccountabilityRoute
  '/app/audit': typeof AppAuditRoute
  '/app/book': typeof AppBookRoute
  '/app/broker': typeof AppBrokerRoute
  '/app/caregiver': typeof AppCaregiverRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/driver': typeof AppDriverRoute
  '/app/facility': typeof AppFacilityRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/riders': typeof AppRidersRouteWithChildren
  '/app/strategy': typeof AppStrategyRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/live-gps/$rideId': typeof AppLiveGpsRideIdRoute
  '/app/registered-riders/$riderId': typeof AppRegisteredRidersRiderIdRoute
  '/app/registered-riders/new': typeof AppRegisteredRidersNewRoute
  '/app/riders/$riderId': typeof AppRidersRiderIdRoute
  '/app/registered-riders': typeof AppRegisteredRidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/accountability': typeof AppAccountabilityRoute
  '/app/audit': typeof AppAuditRoute
  '/app/book': typeof AppBookRoute
  '/app/broker': typeof AppBrokerRoute
  '/app/caregiver': typeof AppCaregiverRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/driver': typeof AppDriverRoute
  '/app/facility': typeof AppFacilityRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/registered-riders': typeof AppRegisteredRidersRouteWithChildren
  '/app/riders': typeof AppRidersRouteWithChildren
  '/app/strategy': typeof AppStrategyRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/live-gps/$rideId': typeof AppLiveGpsRideIdRoute
  '/app/registered-riders/$riderId': typeof AppRegisteredRidersRiderIdRoute
  '/app/registered-riders/new': typeof AppRegisteredRidersNewRoute
  '/app/riders/$riderId': typeof AppRidersRiderIdRoute
  '/app/registered-riders/': typeof AppRegisteredRidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/app/accountability'
    | '/app/audit'
    | '/app/book'
    | '/app/broker'
    | '/app/caregiver'
    | '/app/dashboard'
    | '/app/dispatch'
    | '/app/driver'
    | '/app/facility'
    | '/app/incidents'
    | '/app/providers'
    | '/app/registered-riders'
    | '/app/riders'
    | '/app/strategy'
    | '/app/admin/users'
    | '/app/live-gps/$rideId'
    | '/app/registered-riders/$riderId'
    | '/app/registered-riders/new'
    | '/app/riders/$riderId'
    | '/app/registered-riders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/demo'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/app/accountability'
    | '/app/audit'
    | '/app/book'
    | '/app/broker'
    | '/app/caregiver'
    | '/app/dashboard'
    | '/app/dispatch'
    | '/app/driver'
    | '/app/facility'
    | '/app/incidents'
    | '/app/providers'
    | '/app/riders'
    | '/app/strategy'
    | '/app/admin/users'
    | '/app/live-gps/$rideId'
    | '/app/registered-riders/$riderId'
    | '/app/registered-riders/new'
    | '/app/riders/$riderId'
    | '/app/registered-riders'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/app/accountability'
    | '/app/audit'
    | '/app/book'
    | '/app/broker'
    | '/app/caregiver'
    | '/app/dashboard'
    | '/app/dispatch'
    | '/app/driver'
    | '/app/facility'
    | '/app/incidents'
    | '/app/providers'
    | '/app/registered-riders'
    | '/app/riders'
    | '/app/strategy'
    | '/app/admin/users'
    | '/app/live-gps/$rideId'
    | '/app/registered-riders/$riderId'
    | '/app/registered-riders/new'
    | '/app/riders/$riderId'
    | '/app/registered-riders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/strategy': {
      id: '/app/strategy'
      path: '/strategy'
      fullPath: '/app/strategy'
      preLoaderRoute: typeof AppStrategyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/riders': {
      id: '/app/riders'
      path: '/riders'
      fullPath: '/app/riders'
      preLoaderRoute: typeof AppRidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/registered-riders': {
      id: '/app/registered-riders'
      path: '/registered-riders'
      fullPath: '/app/registered-riders'
      preLoaderRoute: typeof AppRegisteredRidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/providers': {
      id: '/app/providers'
      path: '/providers'
      fullPath: '/app/providers'
      preLoaderRoute: typeof AppProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/incidents': {
      id: '/app/incidents'
      path: '/incidents'
      fullPath: '/app/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/facility': {
      id: '/app/facility'
      path: '/facility'
      fullPath: '/app/facility'
      preLoaderRoute: typeof AppFacilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/driver': {
      id: '/app/driver'
      path: '/driver'
      fullPath: '/app/driver'
      preLoaderRoute: typeof AppDriverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dispatch': {
      id: '/app/dispatch'
      path: '/dispatch'
      fullPath: '/app/dispatch'
      preLoaderRoute: typeof AppDispatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/caregiver': {
      id: '/app/caregiver'
      path: '/caregiver'
      fullPath: '/app/caregiver'
      preLoaderRoute: typeof AppCaregiverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/broker': {
      id: '/app/broker'
      path: '/broker'
      fullPath: '/app/broker'
      preLoaderRoute: typeof AppBrokerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/book': {
      id: '/app/book'
      path: '/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accountability': {
      id: '/app/accountability'
      path: '/accountability'
      fullPath: '/app/accountability'
      preLoaderRoute: typeof AppAccountabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/registered-riders/': {
      id: '/app/registered-riders/'
      path: '/'
      fullPath: '/app/registered-riders/'
      preLoaderRoute: typeof AppRegisteredRidersIndexRouteImport
      parentRoute: typeof AppRegisteredRidersRoute
    }
    '/app/riders/$riderId': {
      id: '/app/riders/$riderId'
      path: '/$riderId'
      fullPath: '/app/riders/$riderId'
      preLoaderRoute: typeof AppRidersRiderIdRouteImport
      parentRoute: typeof AppRidersRoute
    }
    '/app/registered-riders/new': {
      id: '/app/registered-riders/new'
      path: '/new'
      fullPath: '/app/registered-riders/new'
      preLoaderRoute: typeof AppRegisteredRidersNewRouteImport
      parentRoute: typeof AppRegisteredRidersRoute
    }
    '/app/registered-riders/$riderId': {
      id: '/app/registered-riders/$riderId'
      path: '/$riderId'
      fullPath: '/app/registered-riders/$riderId'
      preLoaderRoute: typeof AppRegisteredRidersRiderIdRouteImport
      parentRoute: typeof AppRegisteredRidersRoute
    }
    '/app/live-gps/$rideId': {
      id: '/app/live-gps/$rideId'
      path: '/live-gps/$rideId'
      fullPath: '/app/live-gps/$rideId'
      preLoaderRoute: typeof AppLiveGpsRideIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRegisteredRidersRouteChildren {
  AppRegisteredRidersRiderIdRoute: typeof AppRegisteredRidersRiderIdRoute
  AppRegisteredRidersNewRoute: typeof AppRegisteredRidersNewRoute
  AppRegisteredRidersIndexRoute: typeof AppRegisteredRidersIndexRoute
}

const AppRegisteredRidersRouteChildren: AppRegisteredRidersRouteChildren = {
  AppRegisteredRidersRiderIdRoute: AppRegisteredRidersRiderIdRoute,
  AppRegisteredRidersNewRoute: AppRegisteredRidersNewRoute,
  AppRegisteredRidersIndexRoute: AppRegisteredRidersIndexRoute,
}

const AppRegisteredRidersRouteWithChildren =
  AppRegisteredRidersRoute._addFileChildren(AppRegisteredRidersRouteChildren)

interface AppRidersRouteChildren {
  AppRidersRiderIdRoute: typeof AppRidersRiderIdRoute
}

const AppRidersRouteChildren: AppRidersRouteChildren = {
  AppRidersRiderIdRoute: AppRidersRiderIdRoute,
}

const AppRidersRouteWithChildren = AppRidersRoute._addFileChildren(
  AppRidersRouteChildren,
)

interface AppRouteChildren {
  AppAccountabilityRoute: typeof AppAccountabilityRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBookRoute: typeof AppBookRoute
  AppBrokerRoute: typeof AppBrokerRoute
  AppCaregiverRoute: typeof AppCaregiverRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDispatchRoute: typeof AppDispatchRoute
  AppDriverRoute: typeof AppDriverRoute
  AppFacilityRoute: typeof AppFacilityRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppProvidersRoute: typeof AppProvidersRoute
  AppRegisteredRidersRoute: typeof AppRegisteredRidersRouteWithChildren
  AppRidersRoute: typeof AppRidersRouteWithChildren
  AppStrategyRoute: typeof AppStrategyRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppLiveGpsRideIdRoute: typeof AppLiveGpsRideIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountabilityRoute: AppAccountabilityRoute,
  AppAuditRoute: AppAuditRoute,
  AppBookRoute: AppBookRoute,
  AppBrokerRoute: AppBrokerRoute,
  AppCaregiverRoute: AppCaregiverRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDispatchRoute: AppDispatchRoute,
  AppDriverRoute: AppDriverRoute,
  AppFacilityRoute: AppFacilityRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppProvidersRoute: AppProvidersRoute,
  AppRegisteredRidersRoute: AppRegisteredRidersRouteWithChildren,
  AppRidersRoute: AppRidersRouteWithChildren,
  AppStrategyRoute: AppStrategyRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppLiveGpsRideIdRoute: AppLiveGpsRideIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
